version: '3.8'

services:

  image-store:
    build:
      context: image_store
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - './image_store:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@image-store-db:5432/api_dev
    depends_on:
      - image-store-db

  image-store-db:
    build:
      context: image_store/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  image-sorter:
    build:
      context: image_sorter
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - './image_sorter:/usr/src/app'
    ports:
      - 5005:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
    depends_on:
      - image-store
